### ISSUE TITLE
micro/examples/rp2350: Build failure: Undefined reference to __dso_handle during linking

### ISSUE THREAD

**Issue by miltieIV2** [moonshine-ai/moonshine#204]
I used Google AI Mode to run down this problem and at the end I said:
  "Please generate a summary of this fix so I can open a GitHub issue to share with other people"

---

### Bug Description
When compiling the Moonshine Micro project for the **RP2350 (Pico 2)** target architecture using the specific **arm-none-eabi-gcc 13.3.1** toolchain, the final linking stage fails with linker errors. 

The compiler pulls in hooks for dynamic shared object destruction that do not exist natively in the bare-metal runtime environment. Attempting to bypass this by globally enabling C++ exceptions (`PICO_CXX_ENABLE_EXCEPTIONS`) shifts the failure into **TensorFlow Lite Micro**, breaking its custom embedded memory layout.

---

### Terminal Error Output
```text
/arm-none-eabi/bin/ld: ../../g2p/libg2p.a(g2p_rules.cc.o): in function `g2p::(anonymous namespace)::FunctionWords() [clone .part.0]':
g2p_rules.cc:(.text): undefined reference to `__dso_handle'
/arm-none-eabi/bin/ld: moonshine_micro_echo.elf: hidden symbol `__dso_handle' isn't defined
collect2: error: ld returned 1 exit status
```

---

### Root Cause
The `__dso_handle` and `_fini` symbols are automatically referenced by static initializers and portions of the pre-compiled `libstdc++.a` library. Because the target build is bare-metal, these runtime anchors are missing, causing the linker stage to fail on downstream binaries.

---

### Solution
Provide explicit global fallback stub symbols at the absolute top of the CMake configuration pipeline. This allows all downstream executables and libraries (`libg2p.a`, example binaries) to cleanly share the runtime symbol definition.

Add this code snippet to the top-level **`CMakeLists.txt`** file, immediately following the `project()` initialization statement:

```cmake
# Fix for undefined reference to __dso_handle in bare-metal arm-none-eabi toolchains
if(NOT TARGET toolchain_stubs)
    file(WRITE "\${CMAKE_BINARY_DIR}/toolchain_stubs.c" "void* __dso_handle = 0;\nvoid* _fini = 0;\n")
    add_library(toolchain_stubs STATIC "\${CMAKE_BINARY_DIR}/toolchain_stubs.c")
endif()

# Bind stubs globally to all targets
link_libraries(toolchain_stubs)
```

Once the file is updated, flush the cache and execute a clean build:
```bash
rm -rf build/
examples/rp2350/scripts/build.sh
```

**Comment by petewarden** [comment]
I wasn't able to reproduce it locally, but that may just be a quirk in the exact Arm toolchain, since there are multiple different variants of the same version. I did put in a change to remove global destructors though, which should address the issue. Can you give it a try if you get a chance, and reopen if there are still problems?

**Comment by ihmpartners** [comment]
pulled latest commit and clean built example with same result.

`[ 90%] Building C object examples/rp2350/CMakeFiles/moonshine_micro_echo_hardware.dir/home/ian/pico-sdk/src/rp2_common/pico_thread_local/thread_local.c.o
[ 90%] Building C object examples/rp2350/CMakeFiles/moonshine_micro_echo_hardware.dir/home/ian/pico-sdk/src/rp2_common/pico_multicore/multicore.c.o
[ 90%] Building C object examples/rp2350/CMakeFiles/moonshine_micro_echo_hardware.dir/home/ian/pico-sdk/src/rp2_common/hardware_pio/pio.c.o
[ 90%] Building C object examples/rp2350/CMakeFiles/moonshine_micro_echo_hardware.dir/home/ian/pico-sdk/src/rp2_common/hardware_dma/dma.c.o
[ 90%] Built target moonshine_micro_step6_decoder
/home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/bin/ld: /home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/lib/thumb/v8-m.main+fp/softfp/libstdc++.a(ios_errcat.o): in function `_GLOBAL__sub_I__ZSt17iostream_categoryv':
ios_errcat.cc:(.text.startup._GLOBAL__sub_I__ZSt17iostream_categoryv+0xc): undefined reference to `__dso_handle'
/home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/bin/ld: /home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/lib/thumb/v8-m.main+fp/softfp/libstdc++.a(system_error.o): in function `_GLOBAL__sub_I__ZSt20__throw_system_errori':
system_error.cc:(.text.startup._GLOBAL__sub_I__ZSt20__throw_system_errori+0x1c): undefined reference to `__dso_handle'
/home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/bin/ld: moonshine_micro_echo.elf: hidden symbol `__dso_handle' isn't defined
/home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
gmake[2]: *** [examples/rp2350/CMakeFiles/moonshine_micro_echo.dir/build.make:1662: examples/rp2350/moonshine_micro_echo.elf] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2666: examples/rp2350/CMakeFiles/moonshine_micro_echo.dir/all] Error 2
[ 90%] Linking CXX executable moonshine_micro_echo_hardware.elf
/home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/bin/ld: /home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/lib/thumb/v8-m.main+fp/softfp/libstdc++.a(ios_errcat.o): in function `_GLOBAL__sub_I__ZSt17iostream_categoryv':
ios_errcat.cc:(.text.startup._GLOBAL__sub_I__ZSt17iostream_categoryv+0xc): undefined reference to `__dso_handle'
/home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/bin/ld: /home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/lib/thumb/v8-m.main+fp/softfp/libstdc++.a(system_error.o): in function `_GLOBAL__sub_I__ZSt20__throw_system_errori':
system_error.cc:(.text.startup._GLOBAL__sub_I__ZSt20__throw_system_errori+0x1c): undefined reference to `__dso_handle'
/home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/bin/ld: moonshine_micro_echo_hardware.elf: hidden symbol `__dso_handle' isn't defined
/home/ian/arm-gnu-toolchain-13.3.rel1/bin/../lib/gcc/arm-none-eabi/13.3.1/../../../../arm-none-eabi/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
gmake[2]: *** [examples/rp2350/CMakeFiles/moonshine_micro_echo_hardware.dir/build.make:1726: examples/rp2350/moonshine_micro_echo_hardware.elf] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2703: examples/rp2350/CMakeFiles/moonshine_micro_echo_hardware.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
`

**Comment by petewarden** [comment]
I've done some more investigation and it looks like this is a Pico SDK versioning problem on my side. I was working with v2.2.0, but newer SDKs pass different linker flags, like `-nostartfiles`, so crtbegin.o never makes it into the link.  I've checked a fix into this project's dev-v0.1.6 branch if you'd like to try it now, and it should make it into main next week when 0.1.6 is published.

Please give it a try and let me know how you get on if you have a chance.

**Comment by markwattier1** [comment]
I have this problem, building the main branch, commit 234f60faa0eb388b01cdf7e60aca232af37aefda, I tried the fix above, adding lines to micro/CMakeLists.txt, and removing build/ and re-running examples/rp2350/scripts/build.sh. I still get the following:
build/libstdc++-arm-none-eabi-gDiE7C/libstdc++-arm-none-eabi-17/build/thumb/v8-m.main+fp/softfp/libstdc++/src/c++11/../../../../../../../src/libstdc++-v3/src/c++11/system_error.cc:328: undefined reference to `__dso_handle'
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: moonshine_micro_tts.elf: hidden symbol `__dso_handle' isn't defined

/build/libstdc++-arm-none-eabi-gDiE7C/libstdc++-arm-none-eabi-17/build/thumb/v8-m.main+fp/softfp/libstdc++/src/c++11/../../../../../../../src/libstdc++-v3/src/c++11/system_error.cc:328: undefined reference to `__dso_handle'
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: moonshine_micro_i2s_audio_test.elf: hidden symbol `__dso_handle' isn't defined

This is on linux mint 21.1 Cinnamon.
I am using pico-sdk version 2.3.1. Should I downgrade that? Will the 0.1.6 version of moonshine be available on the main branch soon?
